// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8EueM4BT_JK90ZqIUyIb2tJ3pba-49Y',
    appId: '1:689464516081:web:07b63f1475b677a60b3850',
    messagingSenderId: '689464516081',
    projectId: 'marketly-data',
    authDomain: 'marketly-data.firebaseapp.com',
    storageBucket: 'marketly-data.firebasestorage.app',
    measurementId: 'G-PJDDNDFM54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb7rPo8hlxL2Kq_SgSV08iEGIjZACZjxU',
    appId: '1:689464516081:android:67a2044e39ee55920b3850',
    messagingSenderId: '689464516081',
    projectId: 'marketly-data',
    storageBucket: 'marketly-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNyH83a2f732yDswU-hPXGfP0gcvKUT2Q',
    appId: '1:689464516081:ios:c9fdecf2b18aa4360b3850',
    messagingSenderId: '689464516081',
    projectId: 'marketly-data',
    storageBucket: 'marketly-data.firebasestorage.app',
    iosBundleId: 'com.example.marketly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNyH83a2f732yDswU-hPXGfP0gcvKUT2Q',
    appId: '1:689464516081:ios:c9fdecf2b18aa4360b3850',
    messagingSenderId: '689464516081',
    projectId: 'marketly-data',
    storageBucket: 'marketly-data.firebasestorage.app',
    iosBundleId: 'com.example.marketly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8EueM4BT_JK90ZqIUyIb2tJ3pba-49Y',
    appId: '1:689464516081:web:ae1310c5496e010a0b3850',
    messagingSenderId: '689464516081',
    projectId: 'marketly-data',
    authDomain: 'marketly-data.firebaseapp.com',
    storageBucket: 'marketly-data.firebasestorage.app',
    measurementId: 'G-VR5PVEYJX0',
  );
}
