import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';

class AppHelpers {
  static String formatedDate(Timestamp timestamp) {
    final dateTime = timestamp.toDate();

    final date = DateFormat('d MMMM yyyy').format(dateTime);

    return date;
  }

  static String formatedTime(Timestamp timestamp) {
    final dateTime = timestamp.toDate();
    final time = DateFormat('HH:mm').format(dateTime);
    return time;
  }

  static const locationData = {
    "India": {
      "Gujarat": [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Junagadh",
        "Gandhinagar",
        "Anand",
        "Morbi",
      ],
      "Maharashtra": [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Nashik",
        "Aurangabad",
        "Solapur",
        "Kolhapur",
        "Thane",
        "Amravati",
        "Jalgaon",
      ],
      "Rajasthan": [
        "Jaipur",
        "Udaipur",
        "Jodhpur",
        "Kota",
        "Bikaner",
        "Ajmer",
        "Alwar",
        "Bharatpur",
        "Sikar",
        "Pali",
      ],
      "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Salem",
        "Tiruchirappalli",
        "Erode",
        "Vellore",
        "Thoothukudi",
        "Dindigul",
        "Tirunelveli",
      ],
      "Karnataka": [
        "Bangalore",
        "Mysore",
        "Mangalore",
        "Hubli",
        "Belgaum",
        "Davangere",
        "Shimoga",
        "Tumkur",
        "Udupi",
        "Bidar",
      ],
      "Uttar Pradesh": [
        "Lucknow",
        "Kanpur",
        "Varanasi",
        "Agra",
        "Meerut",
        "Prayagraj",
        "Bareilly",
        "Aligarh",
        "Moradabad",
        "Gorakhpur",
      ],
      "West Bengal": [
        "Kolkata",
        "Howrah",
        "Durgapur",
        "Asansol",
        "Siliguri",
        "Malda",
        "Bardhaman",
        "Kharagpur",
        "Haldia",
        "Darjeeling",
      ],
      "Punjab": [
        "Ludhiana",
        "Amritsar",
        "Jalandhar",
        "Patiala",
        "Bathinda",
        "Mohali",
        "Hoshiarpur",
        "Pathankot",
        "Moga",
        "Firozpur",
      ],
      "Haryana": [
        "Gurgaon",
        "Faridabad",
        "Panipat",
        "Ambala",
        "Hisar",
        "Rohtak",
        "Karnal",
        "Sonipat",
        "Yamunanagar",
        "Panchkula",
      ],
      "Kerala": [
        "Kochi",
        "Thiruvananthapuram",
        "Kozhikode",
        "Thrissur",
        "Alappuzha",
        "Kannur",
        "Kollam",
        "Palakkad",
        "Malappuram",
        "Kottayam",
      ],
    },

    "USA": {
      "California": [
        "Los Angeles",
        "San Diego",
        "San Jose",
        "San Francisco",
        "Fresno",
        "Sacramento",
        "Oakland",
        "Bakersfield",
        "Anaheim",
        "Riverside",
      ],
      "Texas": [
        "Houston",
        "Dallas",
        "Austin",
        "San Antonio",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Plano",
        "Lubbock",
        "Irving",
      ],
      "Florida": [
        "Miami",
        "Orlando",
        "Tampa",
        "Jacksonville",
        "Tallahassee",
        "St. Petersburg",
        "Hialeah",
        "Fort Lauderdale",
        "Cape Coral",
        "Naples",
      ],
      "New York": [
        "New York City",
        "Buffalo",
        "Rochester",
        "Albany",
        "Syracuse",
        "Yonkers",
        "Ithaca",
        "Binghamton",
        "Utica",
        "Schenectady",
      ],
      "Illinois": [
        "Chicago",
        "Aurora",
        "Naperville",
        "Joliet",
        "Rockford",
        "Springfield",
        "Elgin",
        "Peoria",
        "Champaign",
        "Waukegan",
      ],
      "Pennsylvania": [
        "Philadelphia",
        "Pittsburgh",
        "Allentown",
        "Erie",
        "Reading",
        "Scranton",
        "Bethlehem",
        "Lancaster",
        "Harrisburg",
        "York",
      ],
      "Ohio": [
        "Columbus",
        "Cleveland",
        "Cincinnati",
        "Toledo",
        "Akron",
        "Dayton",
        "Parma",
        "Canton",
        "Youngstown",
        "Lorain",
      ],
      "Georgia": [
        "Atlanta",
        "Savannah",
        "Augusta",
        "Columbus",
        "Macon",
        "Athens",
        "Sandy Springs",
        "Roswell",
        "Albany",
        "Johns Creek",
      ],
      "North Carolina": [
        "Charlotte",
        "Raleigh",
        "Greensboro",
        "Durham",
        "Winston-Salem",
        "Fayetteville",
        "Cary",
        "Wilmington",
        "High Point",
        "Asheville",
      ],
      "Michigan": [
        "Detroit",
        "Grand Rapids",
        "Warren",
        "Sterling Heights",
        "Lansing",
        "Ann Arbor",
        "Flint",
        "Dearborn",
        "Livonia",
        "Troy",
      ],
    },

    "Canada": {
      "Ontario": [
        "Toronto",
        "Ottawa",
        "Mississauga",
        "Brampton",
        "Hamilton",
        "London",
        "Markham",
        "Vaughan",
        "Kitchener",
        "Windsor",
      ],
      "Quebec": [
        "Montreal",
        "Quebec City",
        "Laval",
        "Gatineau",
        "Longueuil",
        "Sherbrooke",
        "Saguenay",
        "Levis",
        "Trois-Rivieres",
        "Terrebonne",
      ],
      "British Columbia": [
        "Vancouver",
        "Victoria",
        "Surrey",
        "Burnaby",
        "Richmond",
        "Kelowna",
        "Abbotsford",
        "Nanaimo",
        "Kamloops",
        "Prince George",
      ],
      "Alberta": [
        "Calgary",
        "Edmonton",
        "Red Deer",
        "Lethbridge",
        "St. Albert",
        "Medicine Hat",
        "Grande Prairie",
        "Airdrie",
        "Spruce Grove",
        "Fort McMurray",
      ],
      "Manitoba": [
        "Winnipeg",
        "Brandon",
        "Steinbach",
        "Thompson",
        "Portage la Prairie",
        "Selkirk",
        "Dauphin",
        "Morden",
        "Flin Flon",
        "Winkler",
      ],
      "Saskatchewan": [
        "Saskatoon",
        "Regina",
        "Prince Albert",
        "Moose Jaw",
        "Yorkton",
        "Swift Current",
        "Estevan",
        "North Battleford",
        "Weyburn",
        "Martensville",
      ],
      "Nova Scotia": [
        "Halifax",
        "Sydney",
        "Dartmouth",
        "Truro",
        "New Glasgow",
        "Glace Bay",
        "Kentville",
        "Amherst",
        "Bridgewater",
        "Yarmouth",
      ],
      "New Brunswick": [
        "Moncton",
        "Saint John",
        "Fredericton",
        "Dieppe",
        "Miramichi",
        "Edmundston",
        "Bathurst",
        "Campbellton",
        "Oromocto",
        "Sackville",
      ],
      "Newfoundland": [
        "St. John's",
        "Mount Pearl",
        "Corner Brook",
        "Gander",
        "Grand Falls",
        "Happy Valley",
        "Labrador City",
        "Stephenville",
        "Clarenville",
        "Conception Bay",
      ],
      "Prince Edward Island": [
        "Charlottetown",
        "Summerside",
        "Stratford",
        "Cornwall",
        "Montague",
        "Kensington",
        "Souris",
        "Alberton",
        "Georgetown",
        "Victoria",
      ],
    },
    "Australia": {
      "New South Wales": [
        "Sydney",
        "Newcastle",
        "Wollongong",
        "Albury",
        "Tamworth",
        "Orange",
        "Dubbo",
        "Bathurst",
        "Wagga Wagga",
        "Lismore",
      ],
      "Victoria": [
        "Melbourne",
        "Geelong",
        "Ballarat",
        "Bendigo",
        "Shepparton",
        "Mildura",
        "Warrnambool",
        "Traralgon",
        "Horsham",
        "Wodonga",
      ],
      "Queensland": [
        "Brisbane",
        "Gold Coast",
        "Sunshine Coast",
        "Townsville",
        "Cairns",
        "Toowoomba",
        "Rockhampton",
        "Mackay",
        "Bundaberg",
        "Hervey Bay",
      ],
      "Western Australia": [
        "Perth",
        "Fremantle",
        "Bunbury",
        "Geraldton",
        "Kalgoorlie",
        "Albany",
        "Broome",
        "Karratha",
        "Port Hedland",
        "Esperance",
      ],
      "South Australia": [
        "Adelaide",
        "Mount Gambier",
        "Whyalla",
        "Port Lincoln",
        "Port Augusta",
        "Victor Harbor",
        "Gawler",
        "Murray Bridge",
        "Port Pirie",
        "Kadina",
      ],
      "Tasmania": [
        "Hobart",
        "Launceston",
        "Devonport",
        "Burnie",
        "Ulverstone",
        "Kingston",
        "Sorell",
        "Wynyard",
        "Smithton",
        "Scottsdale",
      ],
      "Northern Territory": [
        "Darwin",
        "Alice Springs",
        "Katherine",
        "Tennant Creek",
        "Nhulunbuy",
        "Palmerston",
        "Jabiru",
        "Yulara",
        "Batchelor",
        "Humpty Doo",
      ],
      "Australian Capital Territory": [
        "Canberra",
        "Belconnen",
        "Tuggeranong",
        "Gungahlin",
        "Woden",
        "Weston Creek",
        "Molonglo",
        "Fyshwick",
        "Narrabundah",
        "Kingston",
      ],
      "Christmas Island": [
        "Flying Fish Cove",
        "Drumsite",
        "Settlement",
        "Poon Saan",
        "Silver City",
        "North West Point",
        "South Point",
        "The Dales",
        "Greta Beach",
        "Ethel Beach",
      ],
      "Cocos Islands": [
        "West Island",
        "Home Island",
        "Direction Island",
        "Horsburgh Island",
        "South Island",
        "Prison Island",
        "Scout Park",
        "Trannies Beach",
        "Oceania House Area",
        "Airstrip Area",
      ],
    },

    "Germany": {
      "Bavaria": [
        "Munich",
        "Nuremberg",
        "Augsburg",
        "Regensburg",
        "Ingolstadt",
        "Wurzburg",
        "Furth",
        "Erlangen",
        "Passau",
        "Bayreuth",
      ],
      "Baden-Wurttemberg": [
        "Stuttgart",
        "Karlsruhe",
        "Mannheim",
        "Freiburg",
        "Heidelberg",
        "Ulm",
        "Pforzheim",
        "Reutlingen",
        "Heilbronn",
        "Tuebingen",
      ],
      "North Rhine-Westphalia": [
        "Cologne",
        "Dusseldorf",
        "Dortmund",
        "Essen",
        "Duisburg",
        "Bochum",
        "Wuppertal",
        "Bonn",
        "Munster",
        "Bielefeld",
      ],
      "Hesse": [
        "Frankfurt",
        "Wiesbaden",
        "Kassel",
        "Darmstadt",
        "Offenbach",
        "Hanau",
        "Giessen",
        "Marburg",
        "Fulda",
        "Rüsselsheim",
      ],
      "Lower Saxony": [
        "Hanover",
        "Braunschweig",
        "Oldenburg",
        "Osnabruck",
        "Wolfsburg",
        "Gottingen",
        "Hildesheim",
        "Salzgitter",
        "Delmenhorst",
        "Lingen",
      ],
      "Saxony": [
        "Leipzig",
        "Dresden",
        "Chemnitz",
        "Zwickau",
        "Plauen",
        "Gorlitz",
        "Bautzen",
        "Freital",
        "Radebeul",
        "Meissen",
      ],
      "Berlin": [
        "Berlin Mitte",
        "Charlottenburg",
        "Kreuzberg",
        "Prenzlauer Berg",
        "Spandau",
        "Neukolln",
        "Friedrichshain",
        "Tempelhof",
        "Lichtenberg",
        "Marzahn",
      ],
      "Hamburg": [
        "Altona",
        "Eimsbuttel",
        "Wandsbek",
        "Bergedorf",
        "Harburg",
        "Hamburg-Mitte",
        "Billstedt",
        "Wilhelmsburg",
        "Blankenese",
        "Finkenwerder",
      ],
      "Brandenburg": [
        "Potsdam",
        "Cottbus",
        "Brandenburg an der Havel",
        "Frankfurt an der Oder",
        "Oranienburg",
        "Falkensee",
        "Bernau",
        "Eberswalde",
        "Schwedt",
        "Senftenberg",
      ],
      "Saarland": [
        "Saarbrucken",
        "Neunkirchen",
        "Homburg",
        "Völklingen",
        "Sankt Ingbert",
        "Merzig",
        "Saarlouis",
        "Dillingen",
        "Lebach",
        "Puttlingen",
      ],
    },
  };
}
